FROM gitpod/workspace-full

USER gitpod

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && \
    echo y|sdk install java"

RUN brew install fzf exa buildpacks/tap/pack kubectl

ENV SHELL=/usr/bin/zsh

ADD https://raw.githubusercontent.com/maeddes/dotfiles/main/.zshrc.full .